# Generated by Django 3.2.7 on 2021-10-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid_buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_type',
            field=models.CharField(choices=[('BID', 'Place Bid'), ('BYN', 'Buy Now')], default='BID', max_length=3),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='bid_buy.bid')),
            ],
        ),
    ]
