# Generated by Django 3.2.7 on 2021-10-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210929_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
    ]
