# Generated by Django 3.2.7 on 2021-10-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='images/auction_categories/')),
            ],
            options={
                'verbose_name_plural': 'Auction Categories',
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='images/auction_items/')),
                ('minimal_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buy_now_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('auction_start', models.DateField()),
                ('auction_end', models.DateField()),
                ('visits_number', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.auctioncategory')),
            ],
        ),
    ]
