# Generated by Django 3.2.7 on 2021-10-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(choices=[('STA', 'Auction Started'), ('EXP', 'Auction Expired'), ('PUR', 'Item Purchased')], default='STA', max_length=3),
        ),
    ]
