# Generated by Django 3.2.7 on 2021-10-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_start',
            field=models.DateTimeField(),
        ),
    ]
